name: sandbox

on: push

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
  FLUTTER_VERSION: 3.22.0

jobs:
  create_dirs:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: create dirs with package
        shell: bash
        run: dart run non_ascii_sandbox --package

      - name: create dirs without package
        shell: bash
        run: dart run non_ascii_sandbox
